import { mkdirSync } from 'node:fs';
import { setSerbianLocale } from './serbianLocale.mjs';
const puppeteer = (await import(process.env.PUPPETEER_CORE ?? 'puppeteer-core')).default;
const SHOTS = process.env.SHOTS_DIR ?? `${import.meta.dirname}/output`;
mkdirSync(SHOTS, { recursive: true });
const BASE = 'http://localhost:3000';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const click = (page, text, nth = 0) => page.evaluate((t, n) => { const b = [...document.querySelectorAll('button')].filter((x) => { const s = x.textContent.replace(/\s+/g, ' ').trim(); return s === t || s.includes(t); })[n]; if (!b) return false; b.click(); return true; }, text, nth);
const shotCard = async (page, name) => { const el = await page.$('div.group.relative.w-full.overflow-hidden, div.w-full > div'); await page.screenshot({ path: `${SHOTS}/${name}.png` }); void el; };
const overflow = (page) => page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1);
// The buttons are found by their Serbian text
const A = await browser.newPage(); await setSerbianLocale(A, BASE); await A.setViewport({ width: 1440, height: 1000 });
await A.goto(`${BASE}/rivals`, { waitUntil: 'networkidle2' });
await A.type('input[placeholder]', 'Vuka');
await sleep(600); await shotCard(A, 'L1-create-1440');
console.log('create overflow', await overflow(A));
await click(A, 'Otvori sobu'); await A.waitForFunction(() => /[A-Z0-9]{6}$/.test(location.pathname), { timeout: 20000 });
const code = A.url().split('/').pop();
await A.waitForFunction(() => document.body.innerText.includes('Spisak trenera'), { timeout: 20000 });
await click(A, 'Izaberi lika');
await A.waitForFunction(() => document.body.innerText.includes('MALI OGLASI')); await click(A, 'Vuka');
await A.waitForFunction(() => document.body.innerText.includes('Spisak trenera'), { timeout: 20000 });
const ctx = await browser.createBrowserContext(); const B = await ctx.newPage(); await setSerbianLocale(B, BASE); await B.setViewport({ width: 390, height: 844 });
await B.goto(`${BASE}/rivals/${code}`, { waitUntil: 'networkidle2' });
await sleep(800); await shotCard(B, 'L2-join-390');
console.log('join overflow', await overflow(B));
await B.type('input[placeholder]', 'Cone');
await click(B, 'Uđi u sobu');
await B.waitForFunction(() => document.body.innerText.includes('Spisak trenera'), { timeout: 20000 });
await click(B, 'Izaberi lika'); await B.waitForFunction(() => document.body.innerText.includes('MALI OGLASI')); await sleep(700);
await shotCard(B, 'L4b-pick-vuka-taken-390');
await click(B, 'Cone');
await B.waitForFunction(() => document.body.innerText.includes('Spisak trenera'), { timeout: 20000 });
await sleep(2500);
await shotCard(A, 'L3-room-1440'); await shotCard(B, 'L4-room-390');
console.log('room overflow', await overflow(A), await overflow(B));
await B.evaluate(() => window.scrollBy(0, 600)); await sleep(300); await shotCard(B, 'L5-room-390-scrolled');
const ctx2 = await browser.createBrowserContext(); const C = await ctx2.newPage(); await setSerbianLocale(C, BASE); await C.setViewport({ width: 1440, height: 1000 });
await C.goto(`${BASE}/rivals`, { waitUntil: 'networkidle2' });
await click(C, 'Uđi u sobu'); await sleep(300); await shotCard(C, 'L6-join-mode-1440');
await browser.close();
console.log('done', code);
